server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: finance-system
          uri: lb://finance-system
          predicates:
            - Path=/system/**

        - id: finance-user
          uri: lb://finance-user
          predicates:
            - Path=/user/**

        - id: finance-product
          uri: lb://finance-product
          predicates:
            - Path=/product/**

        - id: finance-account
          uri: lb://finance-account
          predicates:
            - Path=/account/**

        - id: finance-trade
          uri: lb://finance-trade
          predicates:
            - Path=/trade/**

        - id: finance-message
          uri: lb://finance-message
          predicates:
            - Path=/message/**

        - id: finance-search
          uri: lb://finance-search
          predicates:
            - Path=/search/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns:
              - "http://localhost:3000"
              - "http://localhost:8080"
              - "http://127.0.0.1:3000"
            allowed-headers:
              - "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allow-credentials: true
