# 生产环境配置覆盖

spring:
  datasource:
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
      connection-timeout: 5000
      max-lifetime: 600000
      idle-timeout: 300000

springdoc:
  api-docs:
    enabled: false
